// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/proto/attachment/v1/attachment.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attachment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityType       string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId         string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Filename         string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	OriginalFilename string                 `protobuf:"bytes,5,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	ContentType      string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size             int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	UploaderId       string                 `protobuf:"bytes,8,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_pkg_proto_attachment_v1_attachment_proto_rawDescGZIP(), []int{0}
}

func (x *Attachment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attachment) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *Attachment) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *Attachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Attachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Attachment) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *Attachment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UploadAttachmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadAttachmentRequest_Metadata
	//	*UploadAttachmentRequest_Chunk
	Data          isUploadAttachmentRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAttachmentRequest) Reset() {
	*x = UploadAttachmentRequest{}
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAttachmentRequest) ProtoMessage() {}

func (x *UploadAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAttachmentRequest.ProtoReflect.Descriptor instead.
func (*UploadAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_attachment_v1_attachment_proto_rawDescGZIP(), []int{1}
}

func (x *UploadAttachmentRequest) GetData() isUploadAttachmentRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadAttachmentRequest) GetMetadata() *AttachmentMetadata {
	if x != nil {
		if x, ok := x.Data.(*UploadAttachmentRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadAttachmentRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadAttachmentRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadAttachmentRequest_Data interface {
	isUploadAttachmentRequest_Data()
}

type UploadAttachmentRequest_Metadata struct {
	Metadata *AttachmentMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadAttachmentRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadAttachmentRequest_Metadata) isUploadAttachmentRequest_Data() {}

func (*UploadAttachmentRequest_Chunk) isUploadAttachmentRequest_Data() {}

type AttachmentMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	UploaderId    string                 `protobuf:"bytes,5,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentMetadata) Reset() {
	*x = AttachmentMetadata{}
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentMetadata) ProtoMessage() {}

func (x *AttachmentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentMetadata.ProtoReflect.Descriptor instead.
func (*AttachmentMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_proto_attachment_v1_attachment_proto_rawDescGZIP(), []int{2}
}

func (x *AttachmentMetadata) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *AttachmentMetadata) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AttachmentMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AttachmentMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AttachmentMetadata) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

type UploadAttachmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attachment    *Attachment            `protobuf:"bytes,1,opt,name=attachment,proto3" json:"attachment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAttachmentResponse) Reset() {
	*x = UploadAttachmentResponse{}
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAttachmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAttachmentResponse) ProtoMessage() {}

func (x *UploadAttachmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAttachmentResponse.ProtoReflect.Descriptor instead.
func (*UploadAttachmentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_attachment_v1_attachment_proto_rawDescGZIP(), []int{3}
}

func (x *UploadAttachmentResponse) GetAttachment() *Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

type GetAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttachmentRequest) Reset() {
	*x = GetAttachmentRequest{}
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachmentRequest) ProtoMessage() {}

func (x *GetAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachmentRequest.ProtoReflect.Descriptor instead.
func (*GetAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_attachment_v1_attachment_proto_rawDescGZIP(), []int{4}
}

func (x *GetAttachmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAttachmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attachment    *Attachment            `protobuf:"bytes,1,opt,name=attachment,proto3" json:"attachment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttachmentResponse) Reset() {
	*x = GetAttachmentResponse{}
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttachmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachmentResponse) ProtoMessage() {}

func (x *GetAttachmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachmentResponse.ProtoReflect.Descriptor instead.
func (*GetAttachmentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_attachment_v1_attachment_proto_rawDescGZIP(), []int{5}
}

func (x *GetAttachmentResponse) GetAttachment() *Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

type GetDownloadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  string                 `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLRequest) Reset() {
	*x = GetDownloadURLRequest{}
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLRequest) ProtoMessage() {}

func (x *GetDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_attachment_v1_attachment_proto_rawDescGZIP(), []int{6}
}

func (x *GetDownloadURLRequest) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

type GetDownloadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLResponse) Reset() {
	*x = GetDownloadURLResponse{}
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLResponse) ProtoMessage() {}

func (x *GetDownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_attachment_v1_attachment_proto_rawDescGZIP(), []int{7}
}

func (x *GetDownloadURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetDownloadURLResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type ListAttachmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttachmentsRequest) Reset() {
	*x = ListAttachmentsRequest{}
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttachmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttachmentsRequest) ProtoMessage() {}

func (x *ListAttachmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttachmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAttachmentsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_attachment_v1_attachment_proto_rawDescGZIP(), []int{8}
}

func (x *ListAttachmentsRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ListAttachmentsRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type ListAttachmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attachments   []*Attachment          `protobuf:"bytes,1,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttachmentsResponse) Reset() {
	*x = ListAttachmentsResponse{}
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttachmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttachmentsResponse) ProtoMessage() {}

func (x *ListAttachmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttachmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAttachmentsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_attachment_v1_attachment_proto_rawDescGZIP(), []int{9}
}

func (x *ListAttachmentsResponse) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type DeleteAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  string                 `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttachmentRequest) Reset() {
	*x = DeleteAttachmentRequest{}
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttachmentRequest) ProtoMessage() {}

func (x *DeleteAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttachmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_attachment_v1_attachment_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAttachmentRequest) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

type DeleteAttachmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttachmentResponse) Reset() {
	*x = DeleteAttachmentResponse{}
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttachmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttachmentResponse) ProtoMessage() {}

func (x *DeleteAttachmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_attachment_v1_attachment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttachmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAttachmentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_attachment_v1_attachment_proto_rawDescGZIP(), []int{11}
}

var File_pkg_proto_attachment_v1_attachment_proto protoreflect.FileDescriptor

const file_pkg_proto_attachment_v1_attachment_proto_rawDesc = "" +
	"\n" +
	"(pkg/proto/attachment/v1/attachment.proto\x12\rattachment.v1\"\x9a\x02\n" +
	"\n" +
	"Attachment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12+\n" +
	"\x11original_filename\x18\x05 \x01(\tR\x10originalFilename\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12\x1f\n" +
	"\vuploader_id\x18\b \x01(\tR\n" +
	"uploaderId\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"z\n" +
	"\x17UploadAttachmentRequest\x12?\n" +
	"\bmetadata\x18\x01 \x01(\v2!.attachment.v1.AttachmentMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"\xb2\x01\n" +
	"\x12AttachmentMetadata\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1f\n" +
	"\vuploader_id\x18\x05 \x01(\tR\n" +
	"uploaderId\"U\n" +
	"\x18UploadAttachmentResponse\x129\n" +
	"\n" +
	"attachment\x18\x01 \x01(\v2\x19.attachment.v1.AttachmentR\n" +
	"attachment\"&\n" +
	"\x14GetAttachmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x15GetAttachmentResponse\x129\n" +
	"\n" +
	"attachment\x18\x01 \x01(\v2\x19.attachment.v1.AttachmentR\n" +
	"attachment\"<\n" +
	"\x15GetDownloadURLRequest\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId\"I\n" +
	"\x16GetDownloadURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn\"V\n" +
	"\x16ListAttachmentsRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\"V\n" +
	"\x17ListAttachmentsResponse\x12;\n" +
	"\vattachments\x18\x01 \x03(\v2\x19.attachment.v1.AttachmentR\vattachments\">\n" +
	"\x17DeleteAttachmentRequest\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId\"\x1a\n" +
	"\x18DeleteAttachmentResponse2\xfc\x03\n" +
	"\x11AttachmentService\x12e\n" +
	"\x10UploadAttachment\x12&.attachment.v1.UploadAttachmentRequest\x1a'.attachment.v1.UploadAttachmentResponse(\x01\x12Z\n" +
	"\rGetAttachment\x12#.attachment.v1.GetAttachmentRequest\x1a$.attachment.v1.GetAttachmentResponse\x12]\n" +
	"\x0eGetDownloadURL\x12$.attachment.v1.GetDownloadURLRequest\x1a%.attachment.v1.GetDownloadURLResponse\x12`\n" +
	"\x0fListAttachments\x12%.attachment.v1.ListAttachmentsRequest\x1a&.attachment.v1.ListAttachmentsResponse\x12c\n" +
	"\x10DeleteAttachment\x12&.attachment.v1.DeleteAttachmentRequest\x1a'.attachment.v1.DeleteAttachmentResponseB9Z7github.com/nexusflow/nexusflow/pkg/proto/attachment/v1;b\x06proto3"

var (
	file_pkg_proto_attachment_v1_attachment_proto_rawDescOnce sync.Once
	file_pkg_proto_attachment_v1_attachment_proto_rawDescData []byte
)

func file_pkg_proto_attachment_v1_attachment_proto_rawDescGZIP() []byte {
	file_pkg_proto_attachment_v1_attachment_proto_rawDescOnce.Do(func() {
		file_pkg_proto_attachment_v1_attachment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_attachment_v1_attachment_proto_rawDesc), len(file_pkg_proto_attachment_v1_attachment_proto_rawDesc)))
	})
	return file_pkg_proto_attachment_v1_attachment_proto_rawDescData
}

var file_pkg_proto_attachment_v1_attachment_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_proto_attachment_v1_attachment_proto_goTypes = []any{
	(*Attachment)(nil),               // 0: attachment.v1.Attachment
	(*UploadAttachmentRequest)(nil),  // 1: attachment.v1.UploadAttachmentRequest
	(*AttachmentMetadata)(nil),       // 2: attachment.v1.AttachmentMetadata
	(*UploadAttachmentResponse)(nil), // 3: attachment.v1.UploadAttachmentResponse
	(*GetAttachmentRequest)(nil),     // 4: attachment.v1.GetAttachmentRequest
	(*GetAttachmentResponse)(nil),    // 5: attachment.v1.GetAttachmentResponse
	(*GetDownloadURLRequest)(nil),    // 6: attachment.v1.GetDownloadURLRequest
	(*GetDownloadURLResponse)(nil),   // 7: attachment.v1.GetDownloadURLResponse
	(*ListAttachmentsRequest)(nil),   // 8: attachment.v1.ListAttachmentsRequest
	(*ListAttachmentsResponse)(nil),  // 9: attachment.v1.ListAttachmentsResponse
	(*DeleteAttachmentRequest)(nil),  // 10: attachment.v1.DeleteAttachmentRequest
	(*DeleteAttachmentResponse)(nil), // 11: attachment.v1.DeleteAttachmentResponse
}
var file_pkg_proto_attachment_v1_attachment_proto_depIdxs = []int32{
	2,  // 0: attachment.v1.UploadAttachmentRequest.metadata:type_name -> attachment.v1.AttachmentMetadata
	0,  // 1: attachment.v1.UploadAttachmentResponse.attachment:type_name -> attachment.v1.Attachment
	0,  // 2: attachment.v1.GetAttachmentResponse.attachment:type_name -> attachment.v1.Attachment
	0,  // 3: attachment.v1.ListAttachmentsResponse.attachments:type_name -> attachment.v1.Attachment
	1,  // 4: attachment.v1.AttachmentService.UploadAttachment:input_type -> attachment.v1.UploadAttachmentRequest
	4,  // 5: attachment.v1.AttachmentService.GetAttachment:input_type -> attachment.v1.GetAttachmentRequest
	6,  // 6: attachment.v1.AttachmentService.GetDownloadURL:input_type -> attachment.v1.GetDownloadURLRequest
	8,  // 7: attachment.v1.AttachmentService.ListAttachments:input_type -> attachment.v1.ListAttachmentsRequest
	10, // 8: attachment.v1.AttachmentService.DeleteAttachment:input_type -> attachment.v1.DeleteAttachmentRequest
	3,  // 9: attachment.v1.AttachmentService.UploadAttachment:output_type -> attachment.v1.UploadAttachmentResponse
	5,  // 10: attachment.v1.AttachmentService.GetAttachment:output_type -> attachment.v1.GetAttachmentResponse
	7,  // 11: attachment.v1.AttachmentService.GetDownloadURL:output_type -> attachment.v1.GetDownloadURLResponse
	9,  // 12: attachment.v1.AttachmentService.ListAttachments:output_type -> attachment.v1.ListAttachmentsResponse
	11, // 13: attachment.v1.AttachmentService.DeleteAttachment:output_type -> attachment.v1.DeleteAttachmentResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_attachment_v1_attachment_proto_init() }
func file_pkg_proto_attachment_v1_attachment_proto_init() {
	if File_pkg_proto_attachment_v1_attachment_proto != nil {
		return
	}
	file_pkg_proto_attachment_v1_attachment_proto_msgTypes[1].OneofWrappers = []any{
		(*UploadAttachmentRequest_Metadata)(nil),
		(*UploadAttachmentRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_attachment_v1_attachment_proto_rawDesc), len(file_pkg_proto_attachment_v1_attachment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_attachment_v1_attachment_proto_goTypes,
		DependencyIndexes: file_pkg_proto_attachment_v1_attachment_proto_depIdxs,
		MessageInfos:      file_pkg_proto_attachment_v1_attachment_proto_msgTypes,
	}.Build()
	File_pkg_proto_attachment_v1_attachment_proto = out.File
	file_pkg_proto_attachment_v1_attachment_proto_goTypes = nil
	file_pkg_proto_attachment_v1_attachment_proto_depIdxs = nil
}
