// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/proto/sprint/v1/sprint.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SprintStatus int32

const (
	SprintStatus_SPRINT_STATUS_PLANNED   SprintStatus = 0
	SprintStatus_SPRINT_STATUS_ACTIVE    SprintStatus = 1
	SprintStatus_SPRINT_STATUS_COMPLETED SprintStatus = 2
)

// Enum value maps for SprintStatus.
var (
	SprintStatus_name = map[int32]string{
		0: "SPRINT_STATUS_PLANNED",
		1: "SPRINT_STATUS_ACTIVE",
		2: "SPRINT_STATUS_COMPLETED",
	}
	SprintStatus_value = map[string]int32{
		"SPRINT_STATUS_PLANNED":   0,
		"SPRINT_STATUS_ACTIVE":    1,
		"SPRINT_STATUS_COMPLETED": 2,
	}
)

func (x SprintStatus) Enum() *SprintStatus {
	p := new(SprintStatus)
	*p = x
	return p
}

func (x SprintStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SprintStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_sprint_v1_sprint_proto_enumTypes[0].Descriptor()
}

func (SprintStatus) Type() protoreflect.EnumType {
	return &file_pkg_proto_sprint_v1_sprint_proto_enumTypes[0]
}

func (x SprintStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SprintStatus.Descriptor instead.
func (SprintStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{0}
}

type Sprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Goal          string                 `protobuf:"bytes,4,opt,name=goal,proto3" json:"goal,omitempty"`
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Status        SprintStatus           `protobuf:"varint,7,opt,name=status,proto3,enum=sprint.v1.SprintStatus" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sprint) Reset() {
	*x = Sprint{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sprint) ProtoMessage() {}

func (x *Sprint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sprint.ProtoReflect.Descriptor instead.
func (*Sprint) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{0}
}

func (x *Sprint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sprint) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Sprint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sprint) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *Sprint) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Sprint) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Sprint) GetStatus() SprintStatus {
	if x != nil {
		return x.Status
	}
	return SprintStatus_SPRINT_STATUS_PLANNED
}

func (x *Sprint) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Sprint) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateSprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Goal          string                 `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSprintRequest) Reset() {
	*x = CreateSprintRequest{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSprintRequest) ProtoMessage() {}

func (x *CreateSprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSprintRequest.ProtoReflect.Descriptor instead.
func (*CreateSprintRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSprintRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateSprintRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSprintRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *CreateSprintRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateSprintRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type CreateSprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sprint        *Sprint                `protobuf:"bytes,1,opt,name=sprint,proto3" json:"sprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSprintResponse) Reset() {
	*x = CreateSprintResponse{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSprintResponse) ProtoMessage() {}

func (x *CreateSprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSprintResponse.ProtoReflect.Descriptor instead.
func (*CreateSprintResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSprintResponse) GetSprint() *Sprint {
	if x != nil {
		return x.Sprint
	}
	return nil
}

type GetSprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSprintRequest) Reset() {
	*x = GetSprintRequest{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSprintRequest) ProtoMessage() {}

func (x *GetSprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSprintRequest.ProtoReflect.Descriptor instead.
func (*GetSprintRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{3}
}

func (x *GetSprintRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sprint        *Sprint                `protobuf:"bytes,1,opt,name=sprint,proto3" json:"sprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSprintResponse) Reset() {
	*x = GetSprintResponse{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSprintResponse) ProtoMessage() {}

func (x *GetSprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSprintResponse.ProtoReflect.Descriptor instead.
func (*GetSprintResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{4}
}

func (x *GetSprintResponse) GetSprint() *Sprint {
	if x != nil {
		return x.Sprint
	}
	return nil
}

type ListSprintsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Status        SprintStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=sprint.v1.SprintStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSprintsRequest) Reset() {
	*x = ListSprintsRequest{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSprintsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSprintsRequest) ProtoMessage() {}

func (x *ListSprintsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSprintsRequest.ProtoReflect.Descriptor instead.
func (*ListSprintsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{5}
}

func (x *ListSprintsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListSprintsRequest) GetStatus() SprintStatus {
	if x != nil {
		return x.Status
	}
	return SprintStatus_SPRINT_STATUS_PLANNED
}

type ListSprintsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sprints       []*Sprint              `protobuf:"bytes,1,rep,name=sprints,proto3" json:"sprints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSprintsResponse) Reset() {
	*x = ListSprintsResponse{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSprintsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSprintsResponse) ProtoMessage() {}

func (x *ListSprintsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSprintsResponse.ProtoReflect.Descriptor instead.
func (*ListSprintsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{6}
}

func (x *ListSprintsResponse) GetSprints() []*Sprint {
	if x != nil {
		return x.Sprints
	}
	return nil
}

type UpdateSprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Goal          string                 `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSprintRequest) Reset() {
	*x = UpdateSprintRequest{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSprintRequest) ProtoMessage() {}

func (x *UpdateSprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSprintRequest.ProtoReflect.Descriptor instead.
func (*UpdateSprintRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSprintRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSprintRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSprintRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *UpdateSprintRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *UpdateSprintRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type UpdateSprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sprint        *Sprint                `protobuf:"bytes,1,opt,name=sprint,proto3" json:"sprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSprintResponse) Reset() {
	*x = UpdateSprintResponse{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSprintResponse) ProtoMessage() {}

func (x *UpdateSprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSprintResponse.ProtoReflect.Descriptor instead.
func (*UpdateSprintResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSprintResponse) GetSprint() *Sprint {
	if x != nil {
		return x.Sprint
	}
	return nil
}

type DeleteSprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSprintRequest) Reset() {
	*x = DeleteSprintRequest{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSprintRequest) ProtoMessage() {}

func (x *DeleteSprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSprintRequest.ProtoReflect.Descriptor instead.
func (*DeleteSprintRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSprintRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSprintResponse) Reset() {
	*x = DeleteSprintResponse{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSprintResponse) ProtoMessage() {}

func (x *DeleteSprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSprintResponse.ProtoReflect.Descriptor instead.
func (*DeleteSprintResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{10}
}

type AddIssueToSprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SprintId      string                 `protobuf:"bytes,1,opt,name=sprint_id,json=sprintId,proto3" json:"sprint_id,omitempty"`
	IssueId       string                 `protobuf:"bytes,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddIssueToSprintRequest) Reset() {
	*x = AddIssueToSprintRequest{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddIssueToSprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIssueToSprintRequest) ProtoMessage() {}

func (x *AddIssueToSprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIssueToSprintRequest.ProtoReflect.Descriptor instead.
func (*AddIssueToSprintRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{11}
}

func (x *AddIssueToSprintRequest) GetSprintId() string {
	if x != nil {
		return x.SprintId
	}
	return ""
}

func (x *AddIssueToSprintRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

type AddIssueToSprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddIssueToSprintResponse) Reset() {
	*x = AddIssueToSprintResponse{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddIssueToSprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIssueToSprintResponse) ProtoMessage() {}

func (x *AddIssueToSprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIssueToSprintResponse.ProtoReflect.Descriptor instead.
func (*AddIssueToSprintResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{12}
}

type RemoveIssueFromSprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SprintId      string                 `protobuf:"bytes,1,opt,name=sprint_id,json=sprintId,proto3" json:"sprint_id,omitempty"`
	IssueId       string                 `protobuf:"bytes,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveIssueFromSprintRequest) Reset() {
	*x = RemoveIssueFromSprintRequest{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveIssueFromSprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIssueFromSprintRequest) ProtoMessage() {}

func (x *RemoveIssueFromSprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIssueFromSprintRequest.ProtoReflect.Descriptor instead.
func (*RemoveIssueFromSprintRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveIssueFromSprintRequest) GetSprintId() string {
	if x != nil {
		return x.SprintId
	}
	return ""
}

func (x *RemoveIssueFromSprintRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

type RemoveIssueFromSprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveIssueFromSprintResponse) Reset() {
	*x = RemoveIssueFromSprintResponse{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveIssueFromSprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIssueFromSprintResponse) ProtoMessage() {}

func (x *RemoveIssueFromSprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIssueFromSprintResponse.ProtoReflect.Descriptor instead.
func (*RemoveIssueFromSprintResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{14}
}

type StartSprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SprintId      string                 `protobuf:"bytes,1,opt,name=sprint_id,json=sprintId,proto3" json:"sprint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSprintRequest) Reset() {
	*x = StartSprintRequest{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSprintRequest) ProtoMessage() {}

func (x *StartSprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSprintRequest.ProtoReflect.Descriptor instead.
func (*StartSprintRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{15}
}

func (x *StartSprintRequest) GetSprintId() string {
	if x != nil {
		return x.SprintId
	}
	return ""
}

type StartSprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sprint        *Sprint                `protobuf:"bytes,1,opt,name=sprint,proto3" json:"sprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSprintResponse) Reset() {
	*x = StartSprintResponse{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSprintResponse) ProtoMessage() {}

func (x *StartSprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSprintResponse.ProtoReflect.Descriptor instead.
func (*StartSprintResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{16}
}

func (x *StartSprintResponse) GetSprint() *Sprint {
	if x != nil {
		return x.Sprint
	}
	return nil
}

type CompleteSprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SprintId      string                 `protobuf:"bytes,1,opt,name=sprint_id,json=sprintId,proto3" json:"sprint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteSprintRequest) Reset() {
	*x = CompleteSprintRequest{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSprintRequest) ProtoMessage() {}

func (x *CompleteSprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSprintRequest.ProtoReflect.Descriptor instead.
func (*CompleteSprintRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{17}
}

func (x *CompleteSprintRequest) GetSprintId() string {
	if x != nil {
		return x.SprintId
	}
	return ""
}

type CompleteSprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sprint        *Sprint                `protobuf:"bytes,1,opt,name=sprint,proto3" json:"sprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteSprintResponse) Reset() {
	*x = CompleteSprintResponse{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSprintResponse) ProtoMessage() {}

func (x *CompleteSprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSprintResponse.ProtoReflect.Descriptor instead.
func (*CompleteSprintResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{18}
}

func (x *CompleteSprintResponse) GetSprint() *Sprint {
	if x != nil {
		return x.Sprint
	}
	return nil
}

type GetSprintIssuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SprintId      string                 `protobuf:"bytes,1,opt,name=sprint_id,json=sprintId,proto3" json:"sprint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSprintIssuesRequest) Reset() {
	*x = GetSprintIssuesRequest{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSprintIssuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSprintIssuesRequest) ProtoMessage() {}

func (x *GetSprintIssuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSprintIssuesRequest.ProtoReflect.Descriptor instead.
func (*GetSprintIssuesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{19}
}

func (x *GetSprintIssuesRequest) GetSprintId() string {
	if x != nil {
		return x.SprintId
	}
	return ""
}

type GetSprintIssuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueIds      []string               `protobuf:"bytes,1,rep,name=issue_ids,json=issueIds,proto3" json:"issue_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSprintIssuesResponse) Reset() {
	*x = GetSprintIssuesResponse{}
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSprintIssuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSprintIssuesResponse) ProtoMessage() {}

func (x *GetSprintIssuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sprint_v1_sprint_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSprintIssuesResponse.ProtoReflect.Descriptor instead.
func (*GetSprintIssuesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP(), []int{20}
}

func (x *GetSprintIssuesResponse) GetIssueIds() []string {
	if x != nil {
		return x.IssueIds
	}
	return nil
}

var File_pkg_proto_sprint_v1_sprint_proto protoreflect.FileDescriptor

const file_pkg_proto_sprint_v1_sprint_proto_rawDesc = "" +
	"\n" +
	" pkg/proto/sprint/v1/sprint.proto\x12\tsprint.v1\"\x88\x02\n" +
	"\x06Sprint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04goal\x18\x04 \x01(\tR\x04goal\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12/\n" +
	"\x06status\x18\a \x01(\x0e2\x17.sprint.v1.SprintStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\x96\x01\n" +
	"\x13CreateSprintRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04goal\x18\x03 \x01(\tR\x04goal\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\"A\n" +
	"\x14CreateSprintResponse\x12)\n" +
	"\x06sprint\x18\x01 \x01(\v2\x11.sprint.v1.SprintR\x06sprint\"\"\n" +
	"\x10GetSprintRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x11GetSprintResponse\x12)\n" +
	"\x06sprint\x18\x01 \x01(\v2\x11.sprint.v1.SprintR\x06sprint\"d\n" +
	"\x12ListSprintsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.sprint.v1.SprintStatusR\x06status\"B\n" +
	"\x13ListSprintsResponse\x12+\n" +
	"\asprints\x18\x01 \x03(\v2\x11.sprint.v1.SprintR\asprints\"\x87\x01\n" +
	"\x13UpdateSprintRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04goal\x18\x03 \x01(\tR\x04goal\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\"A\n" +
	"\x14UpdateSprintResponse\x12)\n" +
	"\x06sprint\x18\x01 \x01(\v2\x11.sprint.v1.SprintR\x06sprint\"%\n" +
	"\x13DeleteSprintRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteSprintResponse\"Q\n" +
	"\x17AddIssueToSprintRequest\x12\x1b\n" +
	"\tsprint_id\x18\x01 \x01(\tR\bsprintId\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\tR\aissueId\"\x1a\n" +
	"\x18AddIssueToSprintResponse\"V\n" +
	"\x1cRemoveIssueFromSprintRequest\x12\x1b\n" +
	"\tsprint_id\x18\x01 \x01(\tR\bsprintId\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\tR\aissueId\"\x1f\n" +
	"\x1dRemoveIssueFromSprintResponse\"1\n" +
	"\x12StartSprintRequest\x12\x1b\n" +
	"\tsprint_id\x18\x01 \x01(\tR\bsprintId\"@\n" +
	"\x13StartSprintResponse\x12)\n" +
	"\x06sprint\x18\x01 \x01(\v2\x11.sprint.v1.SprintR\x06sprint\"4\n" +
	"\x15CompleteSprintRequest\x12\x1b\n" +
	"\tsprint_id\x18\x01 \x01(\tR\bsprintId\"C\n" +
	"\x16CompleteSprintResponse\x12)\n" +
	"\x06sprint\x18\x01 \x01(\v2\x11.sprint.v1.SprintR\x06sprint\"5\n" +
	"\x16GetSprintIssuesRequest\x12\x1b\n" +
	"\tsprint_id\x18\x01 \x01(\tR\bsprintId\"6\n" +
	"\x17GetSprintIssuesResponse\x12\x1b\n" +
	"\tissue_ids\x18\x01 \x03(\tR\bissueIds*`\n" +
	"\fSprintStatus\x12\x19\n" +
	"\x15SPRINT_STATUS_PLANNED\x10\x00\x12\x18\n" +
	"\x14SPRINT_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17SPRINT_STATUS_COMPLETED\x10\x022\xe0\x06\n" +
	"\rSprintService\x12O\n" +
	"\fCreateSprint\x12\x1e.sprint.v1.CreateSprintRequest\x1a\x1f.sprint.v1.CreateSprintResponse\x12F\n" +
	"\tGetSprint\x12\x1b.sprint.v1.GetSprintRequest\x1a\x1c.sprint.v1.GetSprintResponse\x12L\n" +
	"\vListSprints\x12\x1d.sprint.v1.ListSprintsRequest\x1a\x1e.sprint.v1.ListSprintsResponse\x12O\n" +
	"\fUpdateSprint\x12\x1e.sprint.v1.UpdateSprintRequest\x1a\x1f.sprint.v1.UpdateSprintResponse\x12O\n" +
	"\fDeleteSprint\x12\x1e.sprint.v1.DeleteSprintRequest\x1a\x1f.sprint.v1.DeleteSprintResponse\x12[\n" +
	"\x10AddIssueToSprint\x12\".sprint.v1.AddIssueToSprintRequest\x1a#.sprint.v1.AddIssueToSprintResponse\x12j\n" +
	"\x15RemoveIssueFromSprint\x12'.sprint.v1.RemoveIssueFromSprintRequest\x1a(.sprint.v1.RemoveIssueFromSprintResponse\x12L\n" +
	"\vStartSprint\x12\x1d.sprint.v1.StartSprintRequest\x1a\x1e.sprint.v1.StartSprintResponse\x12U\n" +
	"\x0eCompleteSprint\x12 .sprint.v1.CompleteSprintRequest\x1a!.sprint.v1.CompleteSprintResponse\x12X\n" +
	"\x0fGetSprintIssues\x12!.sprint.v1.GetSprintIssuesRequest\x1a\".sprint.v1.GetSprintIssuesResponseB5Z3github.com/nexusflow/nexusflow/pkg/proto/sprint/v1;b\x06proto3"

var (
	file_pkg_proto_sprint_v1_sprint_proto_rawDescOnce sync.Once
	file_pkg_proto_sprint_v1_sprint_proto_rawDescData []byte
)

func file_pkg_proto_sprint_v1_sprint_proto_rawDescGZIP() []byte {
	file_pkg_proto_sprint_v1_sprint_proto_rawDescOnce.Do(func() {
		file_pkg_proto_sprint_v1_sprint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_sprint_v1_sprint_proto_rawDesc), len(file_pkg_proto_sprint_v1_sprint_proto_rawDesc)))
	})
	return file_pkg_proto_sprint_v1_sprint_proto_rawDescData
}

var file_pkg_proto_sprint_v1_sprint_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_sprint_v1_sprint_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_pkg_proto_sprint_v1_sprint_proto_goTypes = []any{
	(SprintStatus)(0),                     // 0: sprint.v1.SprintStatus
	(*Sprint)(nil),                        // 1: sprint.v1.Sprint
	(*CreateSprintRequest)(nil),           // 2: sprint.v1.CreateSprintRequest
	(*CreateSprintResponse)(nil),          // 3: sprint.v1.CreateSprintResponse
	(*GetSprintRequest)(nil),              // 4: sprint.v1.GetSprintRequest
	(*GetSprintResponse)(nil),             // 5: sprint.v1.GetSprintResponse
	(*ListSprintsRequest)(nil),            // 6: sprint.v1.ListSprintsRequest
	(*ListSprintsResponse)(nil),           // 7: sprint.v1.ListSprintsResponse
	(*UpdateSprintRequest)(nil),           // 8: sprint.v1.UpdateSprintRequest
	(*UpdateSprintResponse)(nil),          // 9: sprint.v1.UpdateSprintResponse
	(*DeleteSprintRequest)(nil),           // 10: sprint.v1.DeleteSprintRequest
	(*DeleteSprintResponse)(nil),          // 11: sprint.v1.DeleteSprintResponse
	(*AddIssueToSprintRequest)(nil),       // 12: sprint.v1.AddIssueToSprintRequest
	(*AddIssueToSprintResponse)(nil),      // 13: sprint.v1.AddIssueToSprintResponse
	(*RemoveIssueFromSprintRequest)(nil),  // 14: sprint.v1.RemoveIssueFromSprintRequest
	(*RemoveIssueFromSprintResponse)(nil), // 15: sprint.v1.RemoveIssueFromSprintResponse
	(*StartSprintRequest)(nil),            // 16: sprint.v1.StartSprintRequest
	(*StartSprintResponse)(nil),           // 17: sprint.v1.StartSprintResponse
	(*CompleteSprintRequest)(nil),         // 18: sprint.v1.CompleteSprintRequest
	(*CompleteSprintResponse)(nil),        // 19: sprint.v1.CompleteSprintResponse
	(*GetSprintIssuesRequest)(nil),        // 20: sprint.v1.GetSprintIssuesRequest
	(*GetSprintIssuesResponse)(nil),       // 21: sprint.v1.GetSprintIssuesResponse
}
var file_pkg_proto_sprint_v1_sprint_proto_depIdxs = []int32{
	0,  // 0: sprint.v1.Sprint.status:type_name -> sprint.v1.SprintStatus
	1,  // 1: sprint.v1.CreateSprintResponse.sprint:type_name -> sprint.v1.Sprint
	1,  // 2: sprint.v1.GetSprintResponse.sprint:type_name -> sprint.v1.Sprint
	0,  // 3: sprint.v1.ListSprintsRequest.status:type_name -> sprint.v1.SprintStatus
	1,  // 4: sprint.v1.ListSprintsResponse.sprints:type_name -> sprint.v1.Sprint
	1,  // 5: sprint.v1.UpdateSprintResponse.sprint:type_name -> sprint.v1.Sprint
	1,  // 6: sprint.v1.StartSprintResponse.sprint:type_name -> sprint.v1.Sprint
	1,  // 7: sprint.v1.CompleteSprintResponse.sprint:type_name -> sprint.v1.Sprint
	2,  // 8: sprint.v1.SprintService.CreateSprint:input_type -> sprint.v1.CreateSprintRequest
	4,  // 9: sprint.v1.SprintService.GetSprint:input_type -> sprint.v1.GetSprintRequest
	6,  // 10: sprint.v1.SprintService.ListSprints:input_type -> sprint.v1.ListSprintsRequest
	8,  // 11: sprint.v1.SprintService.UpdateSprint:input_type -> sprint.v1.UpdateSprintRequest
	10, // 12: sprint.v1.SprintService.DeleteSprint:input_type -> sprint.v1.DeleteSprintRequest
	12, // 13: sprint.v1.SprintService.AddIssueToSprint:input_type -> sprint.v1.AddIssueToSprintRequest
	14, // 14: sprint.v1.SprintService.RemoveIssueFromSprint:input_type -> sprint.v1.RemoveIssueFromSprintRequest
	16, // 15: sprint.v1.SprintService.StartSprint:input_type -> sprint.v1.StartSprintRequest
	18, // 16: sprint.v1.SprintService.CompleteSprint:input_type -> sprint.v1.CompleteSprintRequest
	20, // 17: sprint.v1.SprintService.GetSprintIssues:input_type -> sprint.v1.GetSprintIssuesRequest
	3,  // 18: sprint.v1.SprintService.CreateSprint:output_type -> sprint.v1.CreateSprintResponse
	5,  // 19: sprint.v1.SprintService.GetSprint:output_type -> sprint.v1.GetSprintResponse
	7,  // 20: sprint.v1.SprintService.ListSprints:output_type -> sprint.v1.ListSprintsResponse
	9,  // 21: sprint.v1.SprintService.UpdateSprint:output_type -> sprint.v1.UpdateSprintResponse
	11, // 22: sprint.v1.SprintService.DeleteSprint:output_type -> sprint.v1.DeleteSprintResponse
	13, // 23: sprint.v1.SprintService.AddIssueToSprint:output_type -> sprint.v1.AddIssueToSprintResponse
	15, // 24: sprint.v1.SprintService.RemoveIssueFromSprint:output_type -> sprint.v1.RemoveIssueFromSprintResponse
	17, // 25: sprint.v1.SprintService.StartSprint:output_type -> sprint.v1.StartSprintResponse
	19, // 26: sprint.v1.SprintService.CompleteSprint:output_type -> sprint.v1.CompleteSprintResponse
	21, // 27: sprint.v1.SprintService.GetSprintIssues:output_type -> sprint.v1.GetSprintIssuesResponse
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_proto_sprint_v1_sprint_proto_init() }
func file_pkg_proto_sprint_v1_sprint_proto_init() {
	if File_pkg_proto_sprint_v1_sprint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_sprint_v1_sprint_proto_rawDesc), len(file_pkg_proto_sprint_v1_sprint_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_sprint_v1_sprint_proto_goTypes,
		DependencyIndexes: file_pkg_proto_sprint_v1_sprint_proto_depIdxs,
		EnumInfos:         file_pkg_proto_sprint_v1_sprint_proto_enumTypes,
		MessageInfos:      file_pkg_proto_sprint_v1_sprint_proto_msgTypes,
	}.Build()
	File_pkg_proto_sprint_v1_sprint_proto = out.File
	file_pkg_proto_sprint_v1_sprint_proto_goTypes = nil
	file_pkg_proto_sprint_v1_sprint_proto_depIdxs = nil
}
