// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: pkg/proto/sprint/v1/sprint.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SprintService_CreateSprint_FullMethodName          = "/sprint.v1.SprintService/CreateSprint"
	SprintService_GetSprint_FullMethodName             = "/sprint.v1.SprintService/GetSprint"
	SprintService_ListSprints_FullMethodName           = "/sprint.v1.SprintService/ListSprints"
	SprintService_UpdateSprint_FullMethodName          = "/sprint.v1.SprintService/UpdateSprint"
	SprintService_DeleteSprint_FullMethodName          = "/sprint.v1.SprintService/DeleteSprint"
	SprintService_AddIssueToSprint_FullMethodName      = "/sprint.v1.SprintService/AddIssueToSprint"
	SprintService_RemoveIssueFromSprint_FullMethodName = "/sprint.v1.SprintService/RemoveIssueFromSprint"
	SprintService_StartSprint_FullMethodName           = "/sprint.v1.SprintService/StartSprint"
	SprintService_CompleteSprint_FullMethodName        = "/sprint.v1.SprintService/CompleteSprint"
	SprintService_GetSprintIssues_FullMethodName       = "/sprint.v1.SprintService/GetSprintIssues"
)

// SprintServiceClient is the client API for SprintService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SprintServiceClient interface {
	CreateSprint(ctx context.Context, in *CreateSprintRequest, opts ...grpc.CallOption) (*CreateSprintResponse, error)
	GetSprint(ctx context.Context, in *GetSprintRequest, opts ...grpc.CallOption) (*GetSprintResponse, error)
	ListSprints(ctx context.Context, in *ListSprintsRequest, opts ...grpc.CallOption) (*ListSprintsResponse, error)
	UpdateSprint(ctx context.Context, in *UpdateSprintRequest, opts ...grpc.CallOption) (*UpdateSprintResponse, error)
	DeleteSprint(ctx context.Context, in *DeleteSprintRequest, opts ...grpc.CallOption) (*DeleteSprintResponse, error)
	AddIssueToSprint(ctx context.Context, in *AddIssueToSprintRequest, opts ...grpc.CallOption) (*AddIssueToSprintResponse, error)
	RemoveIssueFromSprint(ctx context.Context, in *RemoveIssueFromSprintRequest, opts ...grpc.CallOption) (*RemoveIssueFromSprintResponse, error)
	StartSprint(ctx context.Context, in *StartSprintRequest, opts ...grpc.CallOption) (*StartSprintResponse, error)
	CompleteSprint(ctx context.Context, in *CompleteSprintRequest, opts ...grpc.CallOption) (*CompleteSprintResponse, error)
	GetSprintIssues(ctx context.Context, in *GetSprintIssuesRequest, opts ...grpc.CallOption) (*GetSprintIssuesResponse, error)
}

type sprintServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSprintServiceClient(cc grpc.ClientConnInterface) SprintServiceClient {
	return &sprintServiceClient{cc}
}

func (c *sprintServiceClient) CreateSprint(ctx context.Context, in *CreateSprintRequest, opts ...grpc.CallOption) (*CreateSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSprintResponse)
	err := c.cc.Invoke(ctx, SprintService_CreateSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) GetSprint(ctx context.Context, in *GetSprintRequest, opts ...grpc.CallOption) (*GetSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSprintResponse)
	err := c.cc.Invoke(ctx, SprintService_GetSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) ListSprints(ctx context.Context, in *ListSprintsRequest, opts ...grpc.CallOption) (*ListSprintsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSprintsResponse)
	err := c.cc.Invoke(ctx, SprintService_ListSprints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) UpdateSprint(ctx context.Context, in *UpdateSprintRequest, opts ...grpc.CallOption) (*UpdateSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSprintResponse)
	err := c.cc.Invoke(ctx, SprintService_UpdateSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) DeleteSprint(ctx context.Context, in *DeleteSprintRequest, opts ...grpc.CallOption) (*DeleteSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSprintResponse)
	err := c.cc.Invoke(ctx, SprintService_DeleteSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) AddIssueToSprint(ctx context.Context, in *AddIssueToSprintRequest, opts ...grpc.CallOption) (*AddIssueToSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddIssueToSprintResponse)
	err := c.cc.Invoke(ctx, SprintService_AddIssueToSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) RemoveIssueFromSprint(ctx context.Context, in *RemoveIssueFromSprintRequest, opts ...grpc.CallOption) (*RemoveIssueFromSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveIssueFromSprintResponse)
	err := c.cc.Invoke(ctx, SprintService_RemoveIssueFromSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) StartSprint(ctx context.Context, in *StartSprintRequest, opts ...grpc.CallOption) (*StartSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSprintResponse)
	err := c.cc.Invoke(ctx, SprintService_StartSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) CompleteSprint(ctx context.Context, in *CompleteSprintRequest, opts ...grpc.CallOption) (*CompleteSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteSprintResponse)
	err := c.cc.Invoke(ctx, SprintService_CompleteSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) GetSprintIssues(ctx context.Context, in *GetSprintIssuesRequest, opts ...grpc.CallOption) (*GetSprintIssuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSprintIssuesResponse)
	err := c.cc.Invoke(ctx, SprintService_GetSprintIssues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SprintServiceServer is the server API for SprintService service.
// All implementations must embed UnimplementedSprintServiceServer
// for forward compatibility.
type SprintServiceServer interface {
	CreateSprint(context.Context, *CreateSprintRequest) (*CreateSprintResponse, error)
	GetSprint(context.Context, *GetSprintRequest) (*GetSprintResponse, error)
	ListSprints(context.Context, *ListSprintsRequest) (*ListSprintsResponse, error)
	UpdateSprint(context.Context, *UpdateSprintRequest) (*UpdateSprintResponse, error)
	DeleteSprint(context.Context, *DeleteSprintRequest) (*DeleteSprintResponse, error)
	AddIssueToSprint(context.Context, *AddIssueToSprintRequest) (*AddIssueToSprintResponse, error)
	RemoveIssueFromSprint(context.Context, *RemoveIssueFromSprintRequest) (*RemoveIssueFromSprintResponse, error)
	StartSprint(context.Context, *StartSprintRequest) (*StartSprintResponse, error)
	CompleteSprint(context.Context, *CompleteSprintRequest) (*CompleteSprintResponse, error)
	GetSprintIssues(context.Context, *GetSprintIssuesRequest) (*GetSprintIssuesResponse, error)
	mustEmbedUnimplementedSprintServiceServer()
}

// UnimplementedSprintServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSprintServiceServer struct{}

func (UnimplementedSprintServiceServer) CreateSprint(context.Context, *CreateSprintRequest) (*CreateSprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSprint not implemented")
}
func (UnimplementedSprintServiceServer) GetSprint(context.Context, *GetSprintRequest) (*GetSprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSprint not implemented")
}
func (UnimplementedSprintServiceServer) ListSprints(context.Context, *ListSprintsRequest) (*ListSprintsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSprints not implemented")
}
func (UnimplementedSprintServiceServer) UpdateSprint(context.Context, *UpdateSprintRequest) (*UpdateSprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSprint not implemented")
}
func (UnimplementedSprintServiceServer) DeleteSprint(context.Context, *DeleteSprintRequest) (*DeleteSprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSprint not implemented")
}
func (UnimplementedSprintServiceServer) AddIssueToSprint(context.Context, *AddIssueToSprintRequest) (*AddIssueToSprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddIssueToSprint not implemented")
}
func (UnimplementedSprintServiceServer) RemoveIssueFromSprint(context.Context, *RemoveIssueFromSprintRequest) (*RemoveIssueFromSprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveIssueFromSprint not implemented")
}
func (UnimplementedSprintServiceServer) StartSprint(context.Context, *StartSprintRequest) (*StartSprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSprint not implemented")
}
func (UnimplementedSprintServiceServer) CompleteSprint(context.Context, *CompleteSprintRequest) (*CompleteSprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteSprint not implemented")
}
func (UnimplementedSprintServiceServer) GetSprintIssues(context.Context, *GetSprintIssuesRequest) (*GetSprintIssuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSprintIssues not implemented")
}
func (UnimplementedSprintServiceServer) mustEmbedUnimplementedSprintServiceServer() {}
func (UnimplementedSprintServiceServer) testEmbeddedByValue()                       {}

// UnsafeSprintServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SprintServiceServer will
// result in compilation errors.
type UnsafeSprintServiceServer interface {
	mustEmbedUnimplementedSprintServiceServer()
}

func RegisterSprintServiceServer(s grpc.ServiceRegistrar, srv SprintServiceServer) {
	// If the following call pancis, it indicates UnimplementedSprintServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SprintService_ServiceDesc, srv)
}

func _SprintService_CreateSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).CreateSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_CreateSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).CreateSprint(ctx, req.(*CreateSprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_GetSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).GetSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_GetSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).GetSprint(ctx, req.(*GetSprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_ListSprints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSprintsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).ListSprints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_ListSprints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).ListSprints(ctx, req.(*ListSprintsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_UpdateSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).UpdateSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_UpdateSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).UpdateSprint(ctx, req.(*UpdateSprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_DeleteSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).DeleteSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_DeleteSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).DeleteSprint(ctx, req.(*DeleteSprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_AddIssueToSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIssueToSprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).AddIssueToSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_AddIssueToSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).AddIssueToSprint(ctx, req.(*AddIssueToSprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_RemoveIssueFromSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveIssueFromSprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).RemoveIssueFromSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_RemoveIssueFromSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).RemoveIssueFromSprint(ctx, req.(*RemoveIssueFromSprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_StartSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).StartSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_StartSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).StartSprint(ctx, req.(*StartSprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_CompleteSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteSprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).CompleteSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_CompleteSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).CompleteSprint(ctx, req.(*CompleteSprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_GetSprintIssues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSprintIssuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).GetSprintIssues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_GetSprintIssues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).GetSprintIssues(ctx, req.(*GetSprintIssuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SprintService_ServiceDesc is the grpc.ServiceDesc for SprintService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SprintService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sprint.v1.SprintService",
	HandlerType: (*SprintServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSprint",
			Handler:    _SprintService_CreateSprint_Handler,
		},
		{
			MethodName: "GetSprint",
			Handler:    _SprintService_GetSprint_Handler,
		},
		{
			MethodName: "ListSprints",
			Handler:    _SprintService_ListSprints_Handler,
		},
		{
			MethodName: "UpdateSprint",
			Handler:    _SprintService_UpdateSprint_Handler,
		},
		{
			MethodName: "DeleteSprint",
			Handler:    _SprintService_DeleteSprint_Handler,
		},
		{
			MethodName: "AddIssueToSprint",
			Handler:    _SprintService_AddIssueToSprint_Handler,
		},
		{
			MethodName: "RemoveIssueFromSprint",
			Handler:    _SprintService_RemoveIssueFromSprint_Handler,
		},
		{
			MethodName: "StartSprint",
			Handler:    _SprintService_StartSprint_Handler,
		},
		{
			MethodName: "CompleteSprint",
			Handler:    _SprintService_CompleteSprint_Handler,
		},
		{
			MethodName: "GetSprintIssues",
			Handler:    _SprintService_GetSprintIssues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/sprint/v1/sprint.proto",
}
