// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/proto/board/v1/board.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Board entity
type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{0}
}

func (x *Board) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Board) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Board) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Board) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Board) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Board) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Card entity
type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	IssueId       string                 `protobuf:"bytes,3,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{1}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *Card) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *Card) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Card) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Card) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Requests and responses
type CreateBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardRequest) Reset() {
	*x = CreateBoardRequest{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardRequest) ProtoMessage() {}

func (x *CreateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardRequest.ProtoReflect.Descriptor instead.
func (*CreateBoardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBoardRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateBoardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBoardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardResponse) Reset() {
	*x = CreateBoardResponse{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardResponse) ProtoMessage() {}

func (x *CreateBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardResponse.ProtoReflect.Descriptor instead.
func (*CreateBoardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBoardResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type GetBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardRequest) Reset() {
	*x = GetBoardRequest{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardRequest) ProtoMessage() {}

func (x *GetBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardRequest.ProtoReflect.Descriptor instead.
func (*GetBoardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{4}
}

func (x *GetBoardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardResponse) Reset() {
	*x = GetBoardResponse{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardResponse) ProtoMessage() {}

func (x *GetBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardResponse.ProtoReflect.Descriptor instead.
func (*GetBoardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{5}
}

func (x *GetBoardResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type ListBoardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoardsRequest) Reset() {
	*x = ListBoardsRequest{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoardsRequest) ProtoMessage() {}

func (x *ListBoardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoardsRequest.ProtoReflect.Descriptor instead.
func (*ListBoardsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{6}
}

func (x *ListBoardsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListBoardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boards        []*Board               `protobuf:"bytes,1,rep,name=boards,proto3" json:"boards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoardsResponse) Reset() {
	*x = ListBoardsResponse{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoardsResponse) ProtoMessage() {}

func (x *ListBoardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoardsResponse.ProtoReflect.Descriptor instead.
func (*ListBoardsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{7}
}

func (x *ListBoardsResponse) GetBoards() []*Board {
	if x != nil {
		return x.Boards
	}
	return nil
}

type UpdateBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardRequest) Reset() {
	*x = UpdateBoardRequest{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardRequest) ProtoMessage() {}

func (x *UpdateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardRequest.ProtoReflect.Descriptor instead.
func (*UpdateBoardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBoardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBoardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBoardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardResponse) Reset() {
	*x = UpdateBoardResponse{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardResponse) ProtoMessage() {}

func (x *UpdateBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardResponse.ProtoReflect.Descriptor instead.
func (*UpdateBoardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateBoardResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type DeleteBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBoardRequest) Reset() {
	*x = DeleteBoardRequest{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBoardRequest) ProtoMessage() {}

func (x *DeleteBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBoardRequest.ProtoReflect.Descriptor instead.
func (*DeleteBoardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBoardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBoardResponse) Reset() {
	*x = DeleteBoardResponse{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBoardResponse) ProtoMessage() {}

func (x *DeleteBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBoardResponse.ProtoReflect.Descriptor instead.
func (*DeleteBoardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{11}
}

type AddCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	IssueId       string                 `protobuf:"bytes,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Position      int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCardRequest) Reset() {
	*x = AddCardRequest{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCardRequest) ProtoMessage() {}

func (x *AddCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCardRequest.ProtoReflect.Descriptor instead.
func (*AddCardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{12}
}

func (x *AddCardRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *AddCardRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *AddCardRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type AddCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCardResponse) Reset() {
	*x = AddCardResponse{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCardResponse) ProtoMessage() {}

func (x *AddCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCardResponse.ProtoReflect.Descriptor instead.
func (*AddCardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{13}
}

func (x *AddCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type MoveCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	NewPosition   int32                  `protobuf:"varint,2,opt,name=new_position,json=newPosition,proto3" json:"new_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveCardRequest) Reset() {
	*x = MoveCardRequest{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveCardRequest) ProtoMessage() {}

func (x *MoveCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveCardRequest.ProtoReflect.Descriptor instead.
func (*MoveCardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{14}
}

func (x *MoveCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *MoveCardRequest) GetNewPosition() int32 {
	if x != nil {
		return x.NewPosition
	}
	return 0
}

type MoveCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveCardResponse) Reset() {
	*x = MoveCardResponse{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveCardResponse) ProtoMessage() {}

func (x *MoveCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveCardResponse.ProtoReflect.Descriptor instead.
func (*MoveCardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{15}
}

func (x *MoveCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type DeleteCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type DeleteCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardResponse) Reset() {
	*x = DeleteCardResponse{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardResponse) ProtoMessage() {}

func (x *DeleteCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardResponse.ProtoReflect.Descriptor instead.
func (*DeleteCardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{17}
}

type ListCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsRequest) Reset() {
	*x = ListCardsRequest{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsRequest) ProtoMessage() {}

func (x *ListCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsRequest.ProtoReflect.Descriptor instead.
func (*ListCardsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{18}
}

func (x *ListCardsRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

type ListCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsResponse) Reset() {
	*x = ListCardsResponse{}
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsResponse) ProtoMessage() {}

func (x *ListCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_board_v1_board_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsResponse.ProtoReflect.Descriptor instead.
func (*ListCardsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_board_v1_board_proto_rawDescGZIP(), []int{19}
}

func (x *ListCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

var File_pkg_proto_board_v1_board_proto protoreflect.FileDescriptor

const file_pkg_proto_board_v1_board_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/proto/board/v1/board.proto\x12\bboard.v1\"\xaa\x01\n" +
	"\x05Board\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xa6\x01\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\x12\x19\n" +
	"\bissue_id\x18\x03 \x01(\tR\aissueId\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"i\n" +
	"\x12CreateBoardRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"<\n" +
	"\x13CreateBoardResponse\x12%\n" +
	"\x05board\x18\x01 \x01(\v2\x0f.board.v1.BoardR\x05board\"!\n" +
	"\x0fGetBoardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x10GetBoardResponse\x12%\n" +
	"\x05board\x18\x01 \x01(\v2\x0f.board.v1.BoardR\x05board\"2\n" +
	"\x11ListBoardsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"=\n" +
	"\x12ListBoardsResponse\x12'\n" +
	"\x06boards\x18\x01 \x03(\v2\x0f.board.v1.BoardR\x06boards\"Z\n" +
	"\x12UpdateBoardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"<\n" +
	"\x13UpdateBoardResponse\x12%\n" +
	"\x05board\x18\x01 \x01(\v2\x0f.board.v1.BoardR\x05board\"$\n" +
	"\x12DeleteBoardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteBoardResponse\"b\n" +
	"\x0eAddCardRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\tR\aboardId\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\tR\aissueId\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\"5\n" +
	"\x0fAddCardResponse\x12\"\n" +
	"\x04card\x18\x01 \x01(\v2\x0e.board.v1.CardR\x04card\"M\n" +
	"\x0fMoveCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12!\n" +
	"\fnew_position\x18\x02 \x01(\x05R\vnewPosition\"6\n" +
	"\x10MoveCardResponse\x12\"\n" +
	"\x04card\x18\x01 \x01(\v2\x0e.board.v1.CardR\x04card\",\n" +
	"\x11DeleteCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"\x14\n" +
	"\x12DeleteCardResponse\"-\n" +
	"\x10ListCardsRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\tR\aboardId\"9\n" +
	"\x11ListCardsResponse\x12$\n" +
	"\x05cards\x18\x01 \x03(\v2\x0e.board.v1.CardR\x05cards2\x90\x05\n" +
	"\fBoardService\x12J\n" +
	"\vCreateBoard\x12\x1c.board.v1.CreateBoardRequest\x1a\x1d.board.v1.CreateBoardResponse\x12A\n" +
	"\bGetBoard\x12\x19.board.v1.GetBoardRequest\x1a\x1a.board.v1.GetBoardResponse\x12G\n" +
	"\n" +
	"ListBoards\x12\x1b.board.v1.ListBoardsRequest\x1a\x1c.board.v1.ListBoardsResponse\x12J\n" +
	"\vUpdateBoard\x12\x1c.board.v1.UpdateBoardRequest\x1a\x1d.board.v1.UpdateBoardResponse\x12J\n" +
	"\vDeleteBoard\x12\x1c.board.v1.DeleteBoardRequest\x1a\x1d.board.v1.DeleteBoardResponse\x12>\n" +
	"\aAddCard\x12\x18.board.v1.AddCardRequest\x1a\x19.board.v1.AddCardResponse\x12A\n" +
	"\bMoveCard\x12\x19.board.v1.MoveCardRequest\x1a\x1a.board.v1.MoveCardResponse\x12G\n" +
	"\n" +
	"DeleteCard\x12\x1b.board.v1.DeleteCardRequest\x1a\x1c.board.v1.DeleteCardResponse\x12D\n" +
	"\tListCards\x12\x1a.board.v1.ListCardsRequest\x1a\x1b.board.v1.ListCardsResponseB4Z2github.com/nexusflow/nexusflow/pkg/proto/board/v1;b\x06proto3"

var (
	file_pkg_proto_board_v1_board_proto_rawDescOnce sync.Once
	file_pkg_proto_board_v1_board_proto_rawDescData []byte
)

func file_pkg_proto_board_v1_board_proto_rawDescGZIP() []byte {
	file_pkg_proto_board_v1_board_proto_rawDescOnce.Do(func() {
		file_pkg_proto_board_v1_board_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_board_v1_board_proto_rawDesc), len(file_pkg_proto_board_v1_board_proto_rawDesc)))
	})
	return file_pkg_proto_board_v1_board_proto_rawDescData
}

var file_pkg_proto_board_v1_board_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pkg_proto_board_v1_board_proto_goTypes = []any{
	(*Board)(nil),               // 0: board.v1.Board
	(*Card)(nil),                // 1: board.v1.Card
	(*CreateBoardRequest)(nil),  // 2: board.v1.CreateBoardRequest
	(*CreateBoardResponse)(nil), // 3: board.v1.CreateBoardResponse
	(*GetBoardRequest)(nil),     // 4: board.v1.GetBoardRequest
	(*GetBoardResponse)(nil),    // 5: board.v1.GetBoardResponse
	(*ListBoardsRequest)(nil),   // 6: board.v1.ListBoardsRequest
	(*ListBoardsResponse)(nil),  // 7: board.v1.ListBoardsResponse
	(*UpdateBoardRequest)(nil),  // 8: board.v1.UpdateBoardRequest
	(*UpdateBoardResponse)(nil), // 9: board.v1.UpdateBoardResponse
	(*DeleteBoardRequest)(nil),  // 10: board.v1.DeleteBoardRequest
	(*DeleteBoardResponse)(nil), // 11: board.v1.DeleteBoardResponse
	(*AddCardRequest)(nil),      // 12: board.v1.AddCardRequest
	(*AddCardResponse)(nil),     // 13: board.v1.AddCardResponse
	(*MoveCardRequest)(nil),     // 14: board.v1.MoveCardRequest
	(*MoveCardResponse)(nil),    // 15: board.v1.MoveCardResponse
	(*DeleteCardRequest)(nil),   // 16: board.v1.DeleteCardRequest
	(*DeleteCardResponse)(nil),  // 17: board.v1.DeleteCardResponse
	(*ListCardsRequest)(nil),    // 18: board.v1.ListCardsRequest
	(*ListCardsResponse)(nil),   // 19: board.v1.ListCardsResponse
}
var file_pkg_proto_board_v1_board_proto_depIdxs = []int32{
	0,  // 0: board.v1.CreateBoardResponse.board:type_name -> board.v1.Board
	0,  // 1: board.v1.GetBoardResponse.board:type_name -> board.v1.Board
	0,  // 2: board.v1.ListBoardsResponse.boards:type_name -> board.v1.Board
	0,  // 3: board.v1.UpdateBoardResponse.board:type_name -> board.v1.Board
	1,  // 4: board.v1.AddCardResponse.card:type_name -> board.v1.Card
	1,  // 5: board.v1.MoveCardResponse.card:type_name -> board.v1.Card
	1,  // 6: board.v1.ListCardsResponse.cards:type_name -> board.v1.Card
	2,  // 7: board.v1.BoardService.CreateBoard:input_type -> board.v1.CreateBoardRequest
	4,  // 8: board.v1.BoardService.GetBoard:input_type -> board.v1.GetBoardRequest
	6,  // 9: board.v1.BoardService.ListBoards:input_type -> board.v1.ListBoardsRequest
	8,  // 10: board.v1.BoardService.UpdateBoard:input_type -> board.v1.UpdateBoardRequest
	10, // 11: board.v1.BoardService.DeleteBoard:input_type -> board.v1.DeleteBoardRequest
	12, // 12: board.v1.BoardService.AddCard:input_type -> board.v1.AddCardRequest
	14, // 13: board.v1.BoardService.MoveCard:input_type -> board.v1.MoveCardRequest
	16, // 14: board.v1.BoardService.DeleteCard:input_type -> board.v1.DeleteCardRequest
	18, // 15: board.v1.BoardService.ListCards:input_type -> board.v1.ListCardsRequest
	3,  // 16: board.v1.BoardService.CreateBoard:output_type -> board.v1.CreateBoardResponse
	5,  // 17: board.v1.BoardService.GetBoard:output_type -> board.v1.GetBoardResponse
	7,  // 18: board.v1.BoardService.ListBoards:output_type -> board.v1.ListBoardsResponse
	9,  // 19: board.v1.BoardService.UpdateBoard:output_type -> board.v1.UpdateBoardResponse
	11, // 20: board.v1.BoardService.DeleteBoard:output_type -> board.v1.DeleteBoardResponse
	13, // 21: board.v1.BoardService.AddCard:output_type -> board.v1.AddCardResponse
	15, // 22: board.v1.BoardService.MoveCard:output_type -> board.v1.MoveCardResponse
	17, // 23: board.v1.BoardService.DeleteCard:output_type -> board.v1.DeleteCardResponse
	19, // 24: board.v1.BoardService.ListCards:output_type -> board.v1.ListCardsResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_proto_board_v1_board_proto_init() }
func file_pkg_proto_board_v1_board_proto_init() {
	if File_pkg_proto_board_v1_board_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_board_v1_board_proto_rawDesc), len(file_pkg_proto_board_v1_board_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_board_v1_board_proto_goTypes,
		DependencyIndexes: file_pkg_proto_board_v1_board_proto_depIdxs,
		MessageInfos:      file_pkg_proto_board_v1_board_proto_msgTypes,
	}.Build()
	File_pkg_proto_board_v1_board_proto = out.File
	file_pkg_proto_board_v1_board_proto_goTypes = nil
	file_pkg_proto_board_v1_board_proto_depIdxs = nil
}
