// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: pkg/proto/git/v1/git.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GitService_ConnectRepository_FullMethodName    = "/git.v1.GitService/ConnectRepository"
	GitService_ListRepositories_FullMethodName     = "/git.v1.GitService/ListRepositories"
	GitService_GetIssueCommits_FullMethodName      = "/git.v1.GitService/GetIssueCommits"
	GitService_GetIssuePullRequests_FullMethodName = "/git.v1.GitService/GetIssuePullRequests"
)

// GitServiceClient is the client API for GitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GitServiceClient interface {
	ConnectRepository(ctx context.Context, in *ConnectRepositoryRequest, opts ...grpc.CallOption) (*ConnectRepositoryResponse, error)
	ListRepositories(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error)
	GetIssueCommits(ctx context.Context, in *GetIssueCommitsRequest, opts ...grpc.CallOption) (*GetIssueCommitsResponse, error)
	GetIssuePullRequests(ctx context.Context, in *GetIssuePullRequestsRequest, opts ...grpc.CallOption) (*GetIssuePullRequestsResponse, error)
}

type gitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGitServiceClient(cc grpc.ClientConnInterface) GitServiceClient {
	return &gitServiceClient{cc}
}

func (c *gitServiceClient) ConnectRepository(ctx context.Context, in *ConnectRepositoryRequest, opts ...grpc.CallOption) (*ConnectRepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectRepositoryResponse)
	err := c.cc.Invoke(ctx, GitService_ConnectRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) ListRepositories(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRepositoriesResponse)
	err := c.cc.Invoke(ctx, GitService_ListRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) GetIssueCommits(ctx context.Context, in *GetIssueCommitsRequest, opts ...grpc.CallOption) (*GetIssueCommitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIssueCommitsResponse)
	err := c.cc.Invoke(ctx, GitService_GetIssueCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) GetIssuePullRequests(ctx context.Context, in *GetIssuePullRequestsRequest, opts ...grpc.CallOption) (*GetIssuePullRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIssuePullRequestsResponse)
	err := c.cc.Invoke(ctx, GitService_GetIssuePullRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitServiceServer is the server API for GitService service.
// All implementations must embed UnimplementedGitServiceServer
// for forward compatibility.
type GitServiceServer interface {
	ConnectRepository(context.Context, *ConnectRepositoryRequest) (*ConnectRepositoryResponse, error)
	ListRepositories(context.Context, *ListRepositoriesRequest) (*ListRepositoriesResponse, error)
	GetIssueCommits(context.Context, *GetIssueCommitsRequest) (*GetIssueCommitsResponse, error)
	GetIssuePullRequests(context.Context, *GetIssuePullRequestsRequest) (*GetIssuePullRequestsResponse, error)
	mustEmbedUnimplementedGitServiceServer()
}

// UnimplementedGitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGitServiceServer struct{}

func (UnimplementedGitServiceServer) ConnectRepository(context.Context, *ConnectRepositoryRequest) (*ConnectRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectRepository not implemented")
}
func (UnimplementedGitServiceServer) ListRepositories(context.Context, *ListRepositoriesRequest) (*ListRepositoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRepositories not implemented")
}
func (UnimplementedGitServiceServer) GetIssueCommits(context.Context, *GetIssueCommitsRequest) (*GetIssueCommitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIssueCommits not implemented")
}
func (UnimplementedGitServiceServer) GetIssuePullRequests(context.Context, *GetIssuePullRequestsRequest) (*GetIssuePullRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIssuePullRequests not implemented")
}
func (UnimplementedGitServiceServer) mustEmbedUnimplementedGitServiceServer() {}
func (UnimplementedGitServiceServer) testEmbeddedByValue()                    {}

// UnsafeGitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitServiceServer will
// result in compilation errors.
type UnsafeGitServiceServer interface {
	mustEmbedUnimplementedGitServiceServer()
}

func RegisterGitServiceServer(s grpc.ServiceRegistrar, srv GitServiceServer) {
	// If the following call pancis, it indicates UnimplementedGitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GitService_ServiceDesc, srv)
}

func _GitService_ConnectRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).ConnectRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_ConnectRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).ConnectRepository(ctx, req.(*ConnectRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_ListRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRepositoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).ListRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_ListRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).ListRepositories(ctx, req.(*ListRepositoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_GetIssueCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIssueCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).GetIssueCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_GetIssueCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).GetIssueCommits(ctx, req.(*GetIssueCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_GetIssuePullRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIssuePullRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).GetIssuePullRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_GetIssuePullRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).GetIssuePullRequests(ctx, req.(*GetIssuePullRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GitService_ServiceDesc is the grpc.ServiceDesc for GitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "git.v1.GitService",
	HandlerType: (*GitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectRepository",
			Handler:    _GitService_ConnectRepository_Handler,
		},
		{
			MethodName: "ListRepositories",
			Handler:    _GitService_ListRepositories_Handler,
		},
		{
			MethodName: "GetIssueCommits",
			Handler:    _GitService_GetIssueCommits_Handler,
		},
		{
			MethodName: "GetIssuePullRequests",
			Handler:    _GitService_GetIssuePullRequests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/git/v1/git.proto",
}
