// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/project/v1/project.proto

package projectv1

import (
	v1 "github.com/nexusflow/nexusflow/pkg/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Project type
type ProjectType int32

const (
	ProjectType_PROJECT_TYPE_UNSPECIFIED  ProjectType = 0
	ProjectType_PROJECT_TYPE_KANBAN       ProjectType = 1
	ProjectType_PROJECT_TYPE_SCRUM        ProjectType = 2
	ProjectType_PROJECT_TYPE_BUG_TRACKING ProjectType = 3
)

// Enum value maps for ProjectType.
var (
	ProjectType_name = map[int32]string{
		0: "PROJECT_TYPE_UNSPECIFIED",
		1: "PROJECT_TYPE_KANBAN",
		2: "PROJECT_TYPE_SCRUM",
		3: "PROJECT_TYPE_BUG_TRACKING",
	}
	ProjectType_value = map[string]int32{
		"PROJECT_TYPE_UNSPECIFIED":  0,
		"PROJECT_TYPE_KANBAN":       1,
		"PROJECT_TYPE_SCRUM":        2,
		"PROJECT_TYPE_BUG_TRACKING": 3,
	}
)

func (x ProjectType) Enum() *ProjectType {
	p := new(ProjectType)
	*p = x
	return p
}

func (x ProjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_project_v1_project_proto_enumTypes[0].Descriptor()
}

func (ProjectType) Type() protoreflect.EnumType {
	return &file_proto_project_v1_project_proto_enumTypes[0]
}

func (x ProjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectType.Descriptor instead.
func (ProjectType) EnumDescriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{0}
}

// Project status
type ProjectStatus int32

const (
	ProjectStatus_PROJECT_STATUS_UNSPECIFIED ProjectStatus = 0
	ProjectStatus_PROJECT_STATUS_ACTIVE      ProjectStatus = 1
	ProjectStatus_PROJECT_STATUS_ARCHIVED    ProjectStatus = 2
	ProjectStatus_PROJECT_STATUS_DELETED     ProjectStatus = 3
)

// Enum value maps for ProjectStatus.
var (
	ProjectStatus_name = map[int32]string{
		0: "PROJECT_STATUS_UNSPECIFIED",
		1: "PROJECT_STATUS_ACTIVE",
		2: "PROJECT_STATUS_ARCHIVED",
		3: "PROJECT_STATUS_DELETED",
	}
	ProjectStatus_value = map[string]int32{
		"PROJECT_STATUS_UNSPECIFIED": 0,
		"PROJECT_STATUS_ACTIVE":      1,
		"PROJECT_STATUS_ARCHIVED":    2,
		"PROJECT_STATUS_DELETED":     3,
	}
)

func (x ProjectStatus) Enum() *ProjectStatus {
	p := new(ProjectStatus)
	*p = x
	return p
}

func (x ProjectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_project_v1_project_proto_enumTypes[1].Descriptor()
}

func (ProjectStatus) Type() protoreflect.EnumType {
	return &file_proto_project_v1_project_proto_enumTypes[1]
}

func (x ProjectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectStatus.Descriptor instead.
func (ProjectStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{1}
}

// Project role
type ProjectRole int32

const (
	ProjectRole_PROJECT_ROLE_UNSPECIFIED ProjectRole = 0
	ProjectRole_PROJECT_ROLE_ADMIN       ProjectRole = 1
	ProjectRole_PROJECT_ROLE_MEMBER      ProjectRole = 2
	ProjectRole_PROJECT_ROLE_VIEWER      ProjectRole = 3
)

// Enum value maps for ProjectRole.
var (
	ProjectRole_name = map[int32]string{
		0: "PROJECT_ROLE_UNSPECIFIED",
		1: "PROJECT_ROLE_ADMIN",
		2: "PROJECT_ROLE_MEMBER",
		3: "PROJECT_ROLE_VIEWER",
	}
	ProjectRole_value = map[string]int32{
		"PROJECT_ROLE_UNSPECIFIED": 0,
		"PROJECT_ROLE_ADMIN":       1,
		"PROJECT_ROLE_MEMBER":      2,
		"PROJECT_ROLE_VIEWER":      3,
	}
)

func (x ProjectRole) Enum() *ProjectRole {
	p := new(ProjectRole)
	*p = x
	return p
}

func (x ProjectRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_project_v1_project_proto_enumTypes[2].Descriptor()
}

func (ProjectRole) Type() protoreflect.EnumType {
	return &file_proto_project_v1_project_proto_enumTypes[2]
}

func (x ProjectRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectRole.Descriptor instead.
func (ProjectRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{2}
}

// Project entity
type Project struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Key            string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"` // Unique project key (e.g., "PROJ")
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	AvatarUrl      string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Type           ProjectType            `protobuf:"varint,7,opt,name=type,proto3,enum=nexusflow.project.v1.ProjectType" json:"type,omitempty"`
	Status         ProjectStatus          `protobuf:"varint,8,opt,name=status,proto3,enum=nexusflow.project.v1.ProjectStatus" json:"status,omitempty"`
	LeadId         string                 `protobuf:"bytes,9,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	MemberIds      []string               `protobuf:"bytes,10,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	Settings       map[string]string      `protobuf:"bytes,11,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_proto_project_v1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Project) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Project) GetType() ProjectType {
	if x != nil {
		return x.Type
	}
	return ProjectType_PROJECT_TYPE_UNSPECIFIED
}

func (x *Project) GetStatus() ProjectStatus {
	if x != nil {
		return x.Status
	}
	return ProjectStatus_PROJECT_STATUS_UNSPECIFIED
}

func (x *Project) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *Project) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *Project) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Project) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Project) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Project member
type ProjectMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          ProjectRole            `protobuf:"varint,4,opt,name=role,proto3,enum=nexusflow.project.v1.ProjectRole" json:"role,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMember) Reset() {
	*x = ProjectMember{}
	mi := &file_proto_project_v1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMember) ProtoMessage() {}

func (x *ProjectMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMember.ProtoReflect.Descriptor instead.
func (*ProjectMember) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectMember) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProjectMember) GetRole() ProjectRole {
	if x != nil {
		return x.Role
	}
	return ProjectRole_PROJECT_ROLE_UNSPECIFIED
}

func (x *ProjectMember) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

type CreateProjectRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Key            string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type           ProjectType            `protobuf:"varint,5,opt,name=type,proto3,enum=nexusflow.project.v1.ProjectType" json:"type,omitempty"`
	LeadId         string                 `protobuf:"bytes,6,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_proto_project_v1_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProjectRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateProjectRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProjectRequest) GetType() ProjectType {
	if x != nil {
		return x.Type
	}
	return ProjectType_PROJECT_TYPE_UNSPECIFIED
}

func (x *CreateProjectRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

type CreateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_proto_project_v1_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_proto_project_v1_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{4}
}

func (x *GetProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectResponse) Reset() {
	*x = GetProjectResponse{}
	mi := &file_proto_project_v1_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectResponse) ProtoMessage() {}

func (x *GetProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectResponse.ProtoReflect.Descriptor instead.
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{5}
}

func (x *GetProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type GetProjectByKeyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProjectByKeyRequest) Reset() {
	*x = GetProjectByKeyRequest{}
	mi := &file_proto_project_v1_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectByKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectByKeyRequest) ProtoMessage() {}

func (x *GetProjectByKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectByKeyRequest.ProtoReflect.Descriptor instead.
func (*GetProjectByKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{6}
}

func (x *GetProjectByKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetProjectByKeyRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type GetProjectByKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectByKeyResponse) Reset() {
	*x = GetProjectByKeyResponse{}
	mi := &file_proto_project_v1_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectByKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectByKeyResponse) ProtoMessage() {}

func (x *GetProjectByKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectByKeyResponse.ProtoReflect.Descriptor instead.
func (*GetProjectByKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{7}
}

func (x *GetProjectByKeyResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	LeadId        *string                `protobuf:"bytes,5,opt,name=lead_id,json=leadId,proto3,oneof" json:"lead_id,omitempty"`
	Settings      map[string]string      `protobuf:"bytes,6,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_proto_project_v1_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProjectRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProjectRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateProjectRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *UpdateProjectRequest) GetLeadId() string {
	if x != nil && x.LeadId != nil {
		return *x.LeadId
	}
	return ""
}

func (x *UpdateProjectRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectResponse) Reset() {
	*x = UpdateProjectResponse{}
	mi := &file_proto_project_v1_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectResponse) ProtoMessage() {}

func (x *UpdateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectResponse.ProtoReflect.Descriptor instead.
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_proto_project_v1_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.SuccessResponse    `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectResponse) Reset() {
	*x = DeleteProjectResponse{}
	mi := &file_proto_project_v1_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectResponse) ProtoMessage() {}

func (x *DeleteProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteProjectResponse) GetResponse() *v1.SuccessResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type ListProjectsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Pagination     *v1.PaginationRequest  `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Status         ProjectStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=nexusflow.project.v1.ProjectStatus" json:"status,omitempty"`
	Type           ProjectType            `protobuf:"varint,4,opt,name=type,proto3,enum=nexusflow.project.v1.ProjectType" json:"type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_proto_project_v1_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{12}
}

func (x *ListProjectsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListProjectsRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListProjectsRequest) GetStatus() ProjectStatus {
	if x != nil {
		return x.Status
	}
	return ProjectStatus_PROJECT_STATUS_UNSPECIFIED
}

func (x *ListProjectsRequest) GetType() ProjectType {
	if x != nil {
		return x.Type
	}
	return ProjectType_PROJECT_TYPE_UNSPECIFIED
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_proto_project_v1_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{13}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ListProjectsResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ArchiveProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveProjectRequest) Reset() {
	*x = ArchiveProjectRequest{}
	mi := &file_proto_project_v1_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveProjectRequest) ProtoMessage() {}

func (x *ArchiveProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveProjectRequest.ProtoReflect.Descriptor instead.
func (*ArchiveProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{14}
}

func (x *ArchiveProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ArchiveProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveProjectResponse) Reset() {
	*x = ArchiveProjectResponse{}
	mi := &file_proto_project_v1_project_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveProjectResponse) ProtoMessage() {}

func (x *ArchiveProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveProjectResponse.ProtoReflect.Descriptor instead.
func (*ArchiveProjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{15}
}

func (x *ArchiveProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          ProjectRole            `protobuf:"varint,3,opt,name=role,proto3,enum=nexusflow.project.v1.ProjectRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_proto_project_v1_project_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{16}
}

func (x *AddMemberRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AddMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddMemberRequest) GetRole() ProjectRole {
	if x != nil {
		return x.Role
	}
	return ProjectRole_PROJECT_ROLE_UNSPECIFIED
}

type AddMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *ProjectMember         `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	mi := &file_proto_project_v1_project_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResponse.ProtoReflect.Descriptor instead.
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{17}
}

func (x *AddMemberResponse) GetMember() *ProjectMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_proto_project_v1_project_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveMemberRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RemoveMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.SuccessResponse    `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_proto_project_v1_project_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveMemberResponse) GetResponse() *v1.SuccessResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type UpdateMemberRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          ProjectRole            `protobuf:"varint,3,opt,name=role,proto3,enum=nexusflow.project.v1.ProjectRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRoleRequest) Reset() {
	*x = UpdateMemberRoleRequest{}
	mi := &file_proto_project_v1_project_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleRequest) ProtoMessage() {}

func (x *UpdateMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateMemberRoleRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetRole() ProjectRole {
	if x != nil {
		return x.Role
	}
	return ProjectRole_PROJECT_ROLE_UNSPECIFIED
}

type UpdateMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *ProjectMember         `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRoleResponse) Reset() {
	*x = UpdateMemberRoleResponse{}
	mi := &file_proto_project_v1_project_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleResponse) ProtoMessage() {}

func (x *UpdateMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateMemberRoleResponse) GetMember() *ProjectMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_proto_project_v1_project_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{22}
}

func (x *ListMembersRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListMembersRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*ProjectMember       `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_proto_project_v1_project_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_v1_project_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_v1_project_proto_rawDescGZIP(), []int{23}
}

func (x *ListMembersResponse) GetMembers() []*ProjectMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListMembersResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_proto_project_v1_project_proto protoreflect.FileDescriptor

const file_proto_project_v1_project_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/project/v1/project.proto\x12\x14nexusflow.project.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cproto/common/v1/common.proto\"\xd1\x04\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\x125\n" +
	"\x04type\x18\a \x01(\x0e2!.nexusflow.project.v1.ProjectTypeR\x04type\x12;\n" +
	"\x06status\x18\b \x01(\x0e2#.nexusflow.project.v1.ProjectStatusR\x06status\x12\x17\n" +
	"\alead_id\x18\t \x01(\tR\x06leadId\x12\x1d\n" +
	"\n" +
	"member_ids\x18\n" +
	" \x03(\tR\tmemberIds\x12G\n" +
	"\bsettings\x18\v \x03(\v2+.nexusflow.project.v1.Project.SettingsEntryR\bsettings\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc7\x01\n" +
	"\rProjectMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x125\n" +
	"\x04role\x18\x04 \x01(\x0e2!.nexusflow.project.v1.ProjectRoleR\x04role\x127\n" +
	"\tjoined_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"\xd7\x01\n" +
	"\x14CreateProjectRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x125\n" +
	"\x04type\x18\x05 \x01(\x0e2!.nexusflow.project.v1.ProjectTypeR\x04type\x12\x17\n" +
	"\alead_id\x18\x06 \x01(\tR\x06leadId\"P\n" +
	"\x15CreateProjectResponse\x127\n" +
	"\aproject\x18\x01 \x01(\v2\x1d.nexusflow.project.v1.ProjectR\aproject\"#\n" +
	"\x11GetProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x12GetProjectResponse\x127\n" +
	"\aproject\x18\x01 \x01(\v2\x1d.nexusflow.project.v1.ProjectR\aproject\"S\n" +
	"\x16GetProjectByKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"R\n" +
	"\x17GetProjectByKeyResponse\x127\n" +
	"\aproject\x18\x01 \x01(\v2\x1d.nexusflow.project.v1.ProjectR\aproject\"\xef\x02\n" +
	"\x14UpdateProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tH\x02R\tavatarUrl\x88\x01\x01\x12\x1c\n" +
	"\alead_id\x18\x05 \x01(\tH\x03R\x06leadId\x88\x01\x01\x12T\n" +
	"\bsettings\x18\x06 \x03(\v28.nexusflow.project.v1.UpdateProjectRequest.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_avatar_urlB\n" +
	"\n" +
	"\b_lead_id\"P\n" +
	"\x15UpdateProjectResponse\x127\n" +
	"\aproject\x18\x01 \x01(\v2\x1d.nexusflow.project.v1.ProjectR\aproject\"&\n" +
	"\x14DeleteProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Y\n" +
	"\x15DeleteProjectResponse\x12@\n" +
	"\bresponse\x18\x01 \x01(\v2$.nexusflow.common.v1.SuccessResponseR\bresponse\"\xfa\x01\n" +
	"\x13ListProjectsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.nexusflow.common.v1.PaginationRequestR\n" +
	"pagination\x12;\n" +
	"\x06status\x18\x03 \x01(\x0e2#.nexusflow.project.v1.ProjectStatusR\x06status\x125\n" +
	"\x04type\x18\x04 \x01(\x0e2!.nexusflow.project.v1.ProjectTypeR\x04type\"\x9a\x01\n" +
	"\x14ListProjectsResponse\x129\n" +
	"\bprojects\x18\x01 \x03(\v2\x1d.nexusflow.project.v1.ProjectR\bprojects\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.nexusflow.common.v1.PaginationResponseR\n" +
	"pagination\"'\n" +
	"\x15ArchiveProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\x16ArchiveProjectResponse\x127\n" +
	"\aproject\x18\x01 \x01(\v2\x1d.nexusflow.project.v1.ProjectR\aproject\"\x81\x01\n" +
	"\x10AddMemberRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x125\n" +
	"\x04role\x18\x03 \x01(\x0e2!.nexusflow.project.v1.ProjectRoleR\x04role\"P\n" +
	"\x11AddMemberResponse\x12;\n" +
	"\x06member\x18\x01 \x01(\v2#.nexusflow.project.v1.ProjectMemberR\x06member\"M\n" +
	"\x13RemoveMemberRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"X\n" +
	"\x14RemoveMemberResponse\x12@\n" +
	"\bresponse\x18\x01 \x01(\v2$.nexusflow.common.v1.SuccessResponseR\bresponse\"\x88\x01\n" +
	"\x17UpdateMemberRoleRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x125\n" +
	"\x04role\x18\x03 \x01(\x0e2!.nexusflow.project.v1.ProjectRoleR\x04role\"W\n" +
	"\x18UpdateMemberRoleResponse\x12;\n" +
	"\x06member\x18\x01 \x01(\v2#.nexusflow.project.v1.ProjectMemberR\x06member\"{\n" +
	"\x12ListMembersRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.nexusflow.common.v1.PaginationRequestR\n" +
	"pagination\"\x9d\x01\n" +
	"\x13ListMembersResponse\x12=\n" +
	"\amembers\x18\x01 \x03(\v2#.nexusflow.project.v1.ProjectMemberR\amembers\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.nexusflow.common.v1.PaginationResponseR\n" +
	"pagination*{\n" +
	"\vProjectType\x12\x1c\n" +
	"\x18PROJECT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PROJECT_TYPE_KANBAN\x10\x01\x12\x16\n" +
	"\x12PROJECT_TYPE_SCRUM\x10\x02\x12\x1d\n" +
	"\x19PROJECT_TYPE_BUG_TRACKING\x10\x03*\x83\x01\n" +
	"\rProjectStatus\x12\x1e\n" +
	"\x1aPROJECT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PROJECT_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17PROJECT_STATUS_ARCHIVED\x10\x02\x12\x1a\n" +
	"\x16PROJECT_STATUS_DELETED\x10\x03*u\n" +
	"\vProjectRole\x12\x1c\n" +
	"\x18PROJECT_ROLE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PROJECT_ROLE_ADMIN\x10\x01\x12\x17\n" +
	"\x13PROJECT_ROLE_MEMBER\x10\x02\x12\x17\n" +
	"\x13PROJECT_ROLE_VIEWER\x10\x032\x8f\t\n" +
	"\x0eProjectService\x12h\n" +
	"\rCreateProject\x12*.nexusflow.project.v1.CreateProjectRequest\x1a+.nexusflow.project.v1.CreateProjectResponse\x12_\n" +
	"\n" +
	"GetProject\x12'.nexusflow.project.v1.GetProjectRequest\x1a(.nexusflow.project.v1.GetProjectResponse\x12n\n" +
	"\x0fGetProjectByKey\x12,.nexusflow.project.v1.GetProjectByKeyRequest\x1a-.nexusflow.project.v1.GetProjectByKeyResponse\x12h\n" +
	"\rUpdateProject\x12*.nexusflow.project.v1.UpdateProjectRequest\x1a+.nexusflow.project.v1.UpdateProjectResponse\x12h\n" +
	"\rDeleteProject\x12*.nexusflow.project.v1.DeleteProjectRequest\x1a+.nexusflow.project.v1.DeleteProjectResponse\x12e\n" +
	"\fListProjects\x12).nexusflow.project.v1.ListProjectsRequest\x1a*.nexusflow.project.v1.ListProjectsResponse\x12k\n" +
	"\x0eArchiveProject\x12+.nexusflow.project.v1.ArchiveProjectRequest\x1a,.nexusflow.project.v1.ArchiveProjectResponse\x12\\\n" +
	"\tAddMember\x12&.nexusflow.project.v1.AddMemberRequest\x1a'.nexusflow.project.v1.AddMemberResponse\x12e\n" +
	"\fRemoveMember\x12).nexusflow.project.v1.RemoveMemberRequest\x1a*.nexusflow.project.v1.RemoveMemberResponse\x12q\n" +
	"\x10UpdateMemberRole\x12-.nexusflow.project.v1.UpdateMemberRoleRequest\x1a..nexusflow.project.v1.UpdateMemberRoleResponse\x12b\n" +
	"\vListMembers\x12(.nexusflow.project.v1.ListMembersRequest\x1a).nexusflow.project.v1.ListMembersResponseB?Z=github.com/nexusflow/nexusflow/pkg/proto/project/v1;projectv1b\x06proto3"

var (
	file_proto_project_v1_project_proto_rawDescOnce sync.Once
	file_proto_project_v1_project_proto_rawDescData []byte
)

func file_proto_project_v1_project_proto_rawDescGZIP() []byte {
	file_proto_project_v1_project_proto_rawDescOnce.Do(func() {
		file_proto_project_v1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_project_v1_project_proto_rawDesc), len(file_proto_project_v1_project_proto_rawDesc)))
	})
	return file_proto_project_v1_project_proto_rawDescData
}

var file_proto_project_v1_project_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_project_v1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_project_v1_project_proto_goTypes = []any{
	(ProjectType)(0),                 // 0: nexusflow.project.v1.ProjectType
	(ProjectStatus)(0),               // 1: nexusflow.project.v1.ProjectStatus
	(ProjectRole)(0),                 // 2: nexusflow.project.v1.ProjectRole
	(*Project)(nil),                  // 3: nexusflow.project.v1.Project
	(*ProjectMember)(nil),            // 4: nexusflow.project.v1.ProjectMember
	(*CreateProjectRequest)(nil),     // 5: nexusflow.project.v1.CreateProjectRequest
	(*CreateProjectResponse)(nil),    // 6: nexusflow.project.v1.CreateProjectResponse
	(*GetProjectRequest)(nil),        // 7: nexusflow.project.v1.GetProjectRequest
	(*GetProjectResponse)(nil),       // 8: nexusflow.project.v1.GetProjectResponse
	(*GetProjectByKeyRequest)(nil),   // 9: nexusflow.project.v1.GetProjectByKeyRequest
	(*GetProjectByKeyResponse)(nil),  // 10: nexusflow.project.v1.GetProjectByKeyResponse
	(*UpdateProjectRequest)(nil),     // 11: nexusflow.project.v1.UpdateProjectRequest
	(*UpdateProjectResponse)(nil),    // 12: nexusflow.project.v1.UpdateProjectResponse
	(*DeleteProjectRequest)(nil),     // 13: nexusflow.project.v1.DeleteProjectRequest
	(*DeleteProjectResponse)(nil),    // 14: nexusflow.project.v1.DeleteProjectResponse
	(*ListProjectsRequest)(nil),      // 15: nexusflow.project.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),     // 16: nexusflow.project.v1.ListProjectsResponse
	(*ArchiveProjectRequest)(nil),    // 17: nexusflow.project.v1.ArchiveProjectRequest
	(*ArchiveProjectResponse)(nil),   // 18: nexusflow.project.v1.ArchiveProjectResponse
	(*AddMemberRequest)(nil),         // 19: nexusflow.project.v1.AddMemberRequest
	(*AddMemberResponse)(nil),        // 20: nexusflow.project.v1.AddMemberResponse
	(*RemoveMemberRequest)(nil),      // 21: nexusflow.project.v1.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),     // 22: nexusflow.project.v1.RemoveMemberResponse
	(*UpdateMemberRoleRequest)(nil),  // 23: nexusflow.project.v1.UpdateMemberRoleRequest
	(*UpdateMemberRoleResponse)(nil), // 24: nexusflow.project.v1.UpdateMemberRoleResponse
	(*ListMembersRequest)(nil),       // 25: nexusflow.project.v1.ListMembersRequest
	(*ListMembersResponse)(nil),      // 26: nexusflow.project.v1.ListMembersResponse
	nil,                              // 27: nexusflow.project.v1.Project.SettingsEntry
	nil,                              // 28: nexusflow.project.v1.UpdateProjectRequest.SettingsEntry
	(*timestamppb.Timestamp)(nil),    // 29: google.protobuf.Timestamp
	(*v1.SuccessResponse)(nil),       // 30: nexusflow.common.v1.SuccessResponse
	(*v1.PaginationRequest)(nil),     // 31: nexusflow.common.v1.PaginationRequest
	(*v1.PaginationResponse)(nil),    // 32: nexusflow.common.v1.PaginationResponse
}
var file_proto_project_v1_project_proto_depIdxs = []int32{
	0,  // 0: nexusflow.project.v1.Project.type:type_name -> nexusflow.project.v1.ProjectType
	1,  // 1: nexusflow.project.v1.Project.status:type_name -> nexusflow.project.v1.ProjectStatus
	27, // 2: nexusflow.project.v1.Project.settings:type_name -> nexusflow.project.v1.Project.SettingsEntry
	29, // 3: nexusflow.project.v1.Project.created_at:type_name -> google.protobuf.Timestamp
	29, // 4: nexusflow.project.v1.Project.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 5: nexusflow.project.v1.ProjectMember.role:type_name -> nexusflow.project.v1.ProjectRole
	29, // 6: nexusflow.project.v1.ProjectMember.joined_at:type_name -> google.protobuf.Timestamp
	0,  // 7: nexusflow.project.v1.CreateProjectRequest.type:type_name -> nexusflow.project.v1.ProjectType
	3,  // 8: nexusflow.project.v1.CreateProjectResponse.project:type_name -> nexusflow.project.v1.Project
	3,  // 9: nexusflow.project.v1.GetProjectResponse.project:type_name -> nexusflow.project.v1.Project
	3,  // 10: nexusflow.project.v1.GetProjectByKeyResponse.project:type_name -> nexusflow.project.v1.Project
	28, // 11: nexusflow.project.v1.UpdateProjectRequest.settings:type_name -> nexusflow.project.v1.UpdateProjectRequest.SettingsEntry
	3,  // 12: nexusflow.project.v1.UpdateProjectResponse.project:type_name -> nexusflow.project.v1.Project
	30, // 13: nexusflow.project.v1.DeleteProjectResponse.response:type_name -> nexusflow.common.v1.SuccessResponse
	31, // 14: nexusflow.project.v1.ListProjectsRequest.pagination:type_name -> nexusflow.common.v1.PaginationRequest
	1,  // 15: nexusflow.project.v1.ListProjectsRequest.status:type_name -> nexusflow.project.v1.ProjectStatus
	0,  // 16: nexusflow.project.v1.ListProjectsRequest.type:type_name -> nexusflow.project.v1.ProjectType
	3,  // 17: nexusflow.project.v1.ListProjectsResponse.projects:type_name -> nexusflow.project.v1.Project
	32, // 18: nexusflow.project.v1.ListProjectsResponse.pagination:type_name -> nexusflow.common.v1.PaginationResponse
	3,  // 19: nexusflow.project.v1.ArchiveProjectResponse.project:type_name -> nexusflow.project.v1.Project
	2,  // 20: nexusflow.project.v1.AddMemberRequest.role:type_name -> nexusflow.project.v1.ProjectRole
	4,  // 21: nexusflow.project.v1.AddMemberResponse.member:type_name -> nexusflow.project.v1.ProjectMember
	30, // 22: nexusflow.project.v1.RemoveMemberResponse.response:type_name -> nexusflow.common.v1.SuccessResponse
	2,  // 23: nexusflow.project.v1.UpdateMemberRoleRequest.role:type_name -> nexusflow.project.v1.ProjectRole
	4,  // 24: nexusflow.project.v1.UpdateMemberRoleResponse.member:type_name -> nexusflow.project.v1.ProjectMember
	31, // 25: nexusflow.project.v1.ListMembersRequest.pagination:type_name -> nexusflow.common.v1.PaginationRequest
	4,  // 26: nexusflow.project.v1.ListMembersResponse.members:type_name -> nexusflow.project.v1.ProjectMember
	32, // 27: nexusflow.project.v1.ListMembersResponse.pagination:type_name -> nexusflow.common.v1.PaginationResponse
	5,  // 28: nexusflow.project.v1.ProjectService.CreateProject:input_type -> nexusflow.project.v1.CreateProjectRequest
	7,  // 29: nexusflow.project.v1.ProjectService.GetProject:input_type -> nexusflow.project.v1.GetProjectRequest
	9,  // 30: nexusflow.project.v1.ProjectService.GetProjectByKey:input_type -> nexusflow.project.v1.GetProjectByKeyRequest
	11, // 31: nexusflow.project.v1.ProjectService.UpdateProject:input_type -> nexusflow.project.v1.UpdateProjectRequest
	13, // 32: nexusflow.project.v1.ProjectService.DeleteProject:input_type -> nexusflow.project.v1.DeleteProjectRequest
	15, // 33: nexusflow.project.v1.ProjectService.ListProjects:input_type -> nexusflow.project.v1.ListProjectsRequest
	17, // 34: nexusflow.project.v1.ProjectService.ArchiveProject:input_type -> nexusflow.project.v1.ArchiveProjectRequest
	19, // 35: nexusflow.project.v1.ProjectService.AddMember:input_type -> nexusflow.project.v1.AddMemberRequest
	21, // 36: nexusflow.project.v1.ProjectService.RemoveMember:input_type -> nexusflow.project.v1.RemoveMemberRequest
	23, // 37: nexusflow.project.v1.ProjectService.UpdateMemberRole:input_type -> nexusflow.project.v1.UpdateMemberRoleRequest
	25, // 38: nexusflow.project.v1.ProjectService.ListMembers:input_type -> nexusflow.project.v1.ListMembersRequest
	6,  // 39: nexusflow.project.v1.ProjectService.CreateProject:output_type -> nexusflow.project.v1.CreateProjectResponse
	8,  // 40: nexusflow.project.v1.ProjectService.GetProject:output_type -> nexusflow.project.v1.GetProjectResponse
	10, // 41: nexusflow.project.v1.ProjectService.GetProjectByKey:output_type -> nexusflow.project.v1.GetProjectByKeyResponse
	12, // 42: nexusflow.project.v1.ProjectService.UpdateProject:output_type -> nexusflow.project.v1.UpdateProjectResponse
	14, // 43: nexusflow.project.v1.ProjectService.DeleteProject:output_type -> nexusflow.project.v1.DeleteProjectResponse
	16, // 44: nexusflow.project.v1.ProjectService.ListProjects:output_type -> nexusflow.project.v1.ListProjectsResponse
	18, // 45: nexusflow.project.v1.ProjectService.ArchiveProject:output_type -> nexusflow.project.v1.ArchiveProjectResponse
	20, // 46: nexusflow.project.v1.ProjectService.AddMember:output_type -> nexusflow.project.v1.AddMemberResponse
	22, // 47: nexusflow.project.v1.ProjectService.RemoveMember:output_type -> nexusflow.project.v1.RemoveMemberResponse
	24, // 48: nexusflow.project.v1.ProjectService.UpdateMemberRole:output_type -> nexusflow.project.v1.UpdateMemberRoleResponse
	26, // 49: nexusflow.project.v1.ProjectService.ListMembers:output_type -> nexusflow.project.v1.ListMembersResponse
	39, // [39:50] is the sub-list for method output_type
	28, // [28:39] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_project_v1_project_proto_init() }
func file_proto_project_v1_project_proto_init() {
	if File_proto_project_v1_project_proto != nil {
		return
	}
	file_proto_project_v1_project_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_project_v1_project_proto_rawDesc), len(file_proto_project_v1_project_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_project_v1_project_proto_goTypes,
		DependencyIndexes: file_proto_project_v1_project_proto_depIdxs,
		EnumInfos:         file_proto_project_v1_project_proto_enumTypes,
		MessageInfos:      file_proto_project_v1_project_proto_msgTypes,
	}.Build()
	File_proto_project_v1_project_proto = out.File
	file_proto_project_v1_project_proto_goTypes = nil
	file_proto_project_v1_project_proto_depIdxs = nil
}
